apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-guestbook-secrets
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  MYSQL_USER_PASSWORD: {{ .Values.secrets.mysqlUserPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}